# Copyright IBM Corp. 2023, 2024
# Made available under the MIT License

name: "Login to StepZen Server"
author: "IBM"
description: |
  Log into StepZen Server

inputs:
  domain:
    description: "StepZen domain (defaults to stepzen.net)"
    required: true
    default: "stepzen.net"
  account:
    description: "StepZen account name"
    required: true
  adminkey:
    description: "Admin key of the StepZen account - ensure key is masked or comes from GitHub secrets"
    required: true

outputs:
  domain:
    description: "Domain the account is logged into."
    value: ${{ steps.output.outputs.domain }}
  account:
    description: "Account that is logged in."
    value: ${{ steps.output.outputs.account }}
  apikey:
    description: "API key for the account."
    value: ${{ steps.output.outputs.apikey }}

runs:
  using: "composite"
  steps:
    - name: "login"
      run: |
        stepzen login ${{ inputs.domain }} --account ${{ inputs.account }} --adminkey ${{ inputs.adminkey }}
      shell: bash
    - id: output
      run: |
        apikey=$(stepzen whoami --apikey)
        echo "::add-mask::${apikey}"
        echo "domain=$(stepzen whoami --domain)" >> $GITHUB_OUTPUT
        echo "account=${{ inputs.account }}" >> $GITHUB_OUTPUT
        echo "apikey=${apikey}" >> $GITHUB_OUTPUT
      shell: bash
